version: "3.8"

services:
  api-todo-be:
    image: api-todo
    container_name: api-todo-be
    ports:
      - 5001:5001
    networks:
      - redis-epv-network
      - sqlserver-network
    environment:
      - RedisConnection=redis

networks:
  redis-epv-network:
    external: true
  sqlserver-network:
    external: true
  