version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-compose
    ports:
      - 6379:6379
    volumes:
      - type: bind
        source: D:/Lamaran/MINI PROJECT/Redis/Data/
        target: /data
    #  - type: bind
    #    source: D:/Lamaran/MINI PROJECT/Redis/config
    #    target: /usr/local/etc/redis
    #command: ["/usr/local/etc/redis/redis.conf", "/usr/local/etc/redis/redis.conf"]
    networks:
      - todo-network

  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "new_password4"
      # MSSQL_PID: "Express"
    ports:
      - 1433:1433
    volumes:
      - type: bind
        source: D:/Lamaran/MINI PROJECT/SQLServer/Data
        target: /var/opt/mssql/data
    networks:
      - todo-network
        
  api-todo-be:
    image: api-todo
    container_name: api-todo-be
    ports:
      - 5000:5000
    depends_on:
      - redis
      - db-sqlserver
    networks:
      - todo-network
    environment:
      - RedisConnection=redis

networks:
  todo-network:
    driver: bridge